### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by KamDhesi** [MarvalSoftware/MarvalSoftware.Plugins.RequestToDoList#1]
Missing the word sure - should be Please make sure

![image](https://cloud.githubusercontent.com/assets/28095508/25479401/973876aa-2b3c-11e7-9843-56a9a00ec9f1.png)

**Comment by unk1nd** [comment]
https://github.com/MarvalSoftware/MarvalSoftware.Plugins.RequestToDoList/blob/master/index.html#L112

You can edit the text in the index.html file on line 112.

Kindly regards from "Another Marval Administrator"
